### PR TITLE
stuff!

### PR DESCRIPTION
**Pull request by SirEdBr**

### CODE REVIEW

**Comment by SirEdBr** [comment]
Please do it. Plz

**Comment by raehik** [comment]
Not really sure on the details yet, but I think this is a harmless change :)

**Comment by SirEdBr** [comment]
:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by SirEdBr** [comment]
:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by SirEdBr** [comment]
:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by SirEdBr** [comment]
:sob:

**Pull request merged**
